### 配列の要素数がわかるsizeとlenの違い

In [34]:
import numpy as np

* 準備

In [35]:
# 
a = np.arange(0,20)
b = np.reshape(a, (4,5))    # 行数4, 列数5
c = np.reshape(a, (2,2,5))  # 次元数2, 行数2, 列数5

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [39]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


* sizeに関して

In [40]:
# sizeの実行
print(a.size)
print(b.size)
print(c.size)

20
20
20


* lenに関して
    * 多次元配列に適用した場合の動作が異なり, 配列の数を数える

In [41]:
"""
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])
"""
print(len(a))

20


In [42]:
print(len(b))

4


In [43]:
print(len(c))

2


In [44]:
# cにそれぞれアクセスすると結果は以下となる.
print(f"c0: \n{c[0]}")
print(f"c1: \n{c[1]}")


c0: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
c1: 
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [45]:
# listに対しても同じ
a_ = list(a)
b_ = list(b)
c_ = list(c)
print(f"a_:\n{a_}")
print(f"b_:\n{b_}")
print(f"c_:\n{c_}")

a_:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
b_:
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]
c_:
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]


In [46]:
print(len(a_))
print(len(b_))
print(len(c_))

20
4
2


* 参考) numpy, dataframe, list, arrayの違い

In [47]:
# pandasのdataframeはpandasのインストールとimportが必要、複数の型を格納可能。基本的に二次元データまで。
# インデックス・カラム(列)を指定してExcelのように扱える。
# 豊富なメソッドがあり、機械学習のテーブルデータ処理で最もよく利用する。
import pandas as pd
a_df = pd.DataFrame([['a', 'b', 'c'],[4, 5, 6]])
print(f"df:\n{a_df}")


df:
   0  1  2
0  a  b  c
1  4  5  6


In [48]:
# numpyのndarrayはnumpyのインストールとimportが必要、同じ型しか基本は格納できない。多次元配列を表現できる。
# 何より数値計算のメソッドが豊富 & 高速演算が可能。画像処理や機械学習の結果はndarrayで返されることが多い。
a_np = np.array([[1, 2, 3],[4, 5, 6]])
print(f"np:\n{a_np}")

np:
[[1 2 3]
 [4 5 6]]


In [49]:
# listは異なる型を格納できる・import不要・多次元配列を表現可能
a_list = [[1, 2, 3],[4, 5, 6]]
print(f"list:\n{a_list}")

list:
[[1, 2, 3], [4, 5, 6]]


In [ ]:
# arrayは一次元配列のみ・同じ型のみ・importが必要 > 実務で使うことはほぼない
import array
a_array = array.array('i', [1, 2, 3])
print(f"array:\n{a_array}")

In [ ]:
ng_array = array.array('i', [1, 2.0, 3])