# 2章: Numpyの概要を理解しよう

In [ ]:
# numpyの読み込み
import numpy as np

multi_array = np.array([[0, 1, 2], [3, 4, 5]])
display(multi_array)

In [ ]:
type(multi_array)

* ニュートン法
    * 関数のゼロ点(根)を数値的に求める代表的な方法の一つ
    * 簡単に言うと、ニュートン法とは、ある初期値からスタートし、関数のグラフにおける接線の方程式を繰り返し使うことで、次々と関数のゼロ点により近づいていく反復計算法のこと
* 最小二乗法
    * 最小二乗法とは、データの集合に最も適合する関数を見つける手法のことを簡単に言えば以下のようになる
    * 与えられたデータ点の集合(x,y)があるとき、それらの点とある関数f(x)との残差(データ点との誤差)の2乗の合計を最小にするような関数f(x)のパラメータを求める方法
    * 具体的なイメージとしては、例えばデータ点が直線的な分布をしている場合、それらの点にもっとも近い直線y=ax+bを見つけ出すことになる。この直線は、全てのデータ点との残差の2乗の合計が最小になるように決定される
* BLAS
    * Basic Linear Algebra Subprograms
    * 低レベルの線形代数演算をCやFortranで高度に最適化された関数として提供するのがBLASの役割
    * これにより高速化している
* LAPACK
    * LAPACKはFortranで書かれており、BLASよりも上位の線形代数ルーチンを提供する。NumPyはBLASに加えて、内部でLAPACKのルーチンも利用することで、Pythonで高度な線形代数計算を可能


In [ ]:
multi_array = np.array([[0, 1, 2], [3, 4, 5]])
a = [1, 2, 3]
multi_array + a

# 3章 NumPyを使ってみよう

In [2]:
import numpy as np
narray = np.array([1, 2, 3])
display(narray)

array([1, 2, 3])

In [3]:
# サイズ: 配列の要素数のこと
narray.size

3

In [ ]:
# 型の確認
type(narray)

In [ ]:
nones = np.ones(10)
nones

In [ ]:
type(nones)

In [ ]:
# 多次元配列
multi_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
display(multi_array)

In [ ]:
# error
multi_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8, 9]])
multi_array

In [4]:
# 乱数の作成
np.random.rand()

0.9644474357220622

In [5]:
import random

# 0以上1未満の実数値の乱数を生成
random_num = random.random()
print(random_num)

0.1407973868300385


In [6]:
# 乱数 * 3
np.random.rand(3)

array([0.71989447, 0.4458582 , 0.10821226])

In [7]:
display(np.random.rand(3, 3))

array([[0.20190424, 0.42443983, 0.77161826],
       [0.27231651, 0.39574704, 0.266645  ],
       [0.9141821 , 0.77596573, 0.97616432]])

In [11]:
# 整数の乱数
np.random.randint(1, 10)

6

In [13]:
# 整数の乱数の1次元配列
np.random.randint(1, 10, (5,))

array([2, 1, 9, 7, 5])

In [14]:
# 整数の乱数の2次元配列
display(np.random.randint(1, 10, (5,5)))

array([[9, 1, 9, 4, 6],
       [8, 4, 3, 2, 6],
       [4, 9, 9, 1, 7],
       [3, 5, 1, 7, 9],
       [3, 6, 7, 9, 7]])

In [15]:
# 最大値を求める
random_multi_array = np.random.randint(1, 10, (5,5))
display(random_multi_array)
print(f"max:{random_multi_array.max()}")
print(f"min:{random_multi_array.min()}")

array([[1, 8, 9, 5, 6],
       [9, 7, 7, 1, 9],
       [7, 6, 3, 8, 7],
       [7, 8, 5, 5, 6],
       [9, 1, 4, 8, 7]])

max:9
min:1


In [20]:
# スライシングの例(要素番号0～2)
random_array = np.random.randint(1, 10, (10, ))
print(random_array)
print(random_array[0:3])
print(random_array[1:3])
print(random_array[1:])
print(random_array[:1])
print(random_array[-1])


[9 4 9 7 6 9 2 9 3 8]
[9 4 9]
[4 9]
[4 9 7 6 9 2 9 3 8]
[9]
8


In [24]:
list_value: list = [6,4,3,2,9]
list_value[-1]

9

In [25]:
# 配列の結合
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
display(np.concatenate((a, b)))

# 二次元に変換
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
display(np.concatenate((a, b), axis=0))


array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 足し算

# np.onesで1次元配列(値1 * 3)
three = np.ones(3)
display(three)

# 加算
display(three + 3)

# 加算
display(three + [1, 0, 1])

In [ ]:
# arange: 0~5の配列。これを2行3列へ変換する。
six_reshape = np.arange(6).reshape(2, 3)
display(six_reshape)
display(six_reshape + 1)
display(six_reshape + np.array([[1, 0, 2], [1, 0, 2]]))

In [ ]:
# 引き算
five_full = np.full(5, 5)
display(five_full)
display(five_full - 2)
display(five_full - np.array([1, 2, 3, 4, 5]))

In [ ]:
# 掛け算
ten = np.arange(10)
display(ten)
display(ten * 3)
display(ten * np.array([1, 2, 2, 2, 3, 3, 3, 4, 4, 5]))

In [ ]:
# 割り算
div_six = np.arange(6)
display(div_six)
display(div_six / 2)

In [ ]:
# 行列演算（アダマール積）
A = np.array([[4, 7, 2], [1, 2, 1]])
B = np.array([[2, 2, 2], [4, 5, 2], [9, 2, 1]])
display(A)
display(B)

display(np.dot(A, B))



In [ ]:
# 逆行列
from numpy.linalg import inv
A = np.array([[1, 1, 0], [0, 1, 0], [0, 0, 1]])
ainv = inv(A)
display(ainv)

# 単位行列への変換
display(np.dot(A, ainv))

In [ ]:
# 合計値
a = np.array([1, 2, 3])
display(np.sum(a))

a = np.array([[14, 8, 11, 10], [7, 9, 10, 11], [10, 15, 5, 10]])
display(np.sum(a))
display(np.sum(a, axis=0))
display(np.sum(a, axis=1))


In [ ]:
# 中央値
a = np.array([1,2,3,4])
display(np.median(a))


In [ ]:
# 標準偏差: std
a = np.array([1, 2, 3, 4, 5])
display(np.std(a))


In [ ]:
# 画像処理
from PIL import Image
import numpy as np

# 画像を読み込む
im = Image.open("camera.jpg")

# //2: 割り算＆切り捨て
im = im.resize((im.width //2, im.height //2)) # 元の画像はデカいので縮小
display(im)


In [ ]:
im_np = np.asarray(im)
display(im_np)

In [ ]:
display(255 - im_np)

In [ ]:
# ネガティブ画像へ変換する（ブロードキャストが機能する）
negative_im_np = 255 - im_np
negative_im = Image.fromarray(negative_im_np)
display(negative_im)


# 課題: NumPyで配列の操作や演算をしよう

In [ ]:
data-analysis-basic-kadaiリポジトリへ格納する。

# 演習3-1
* 行列の積(アダマール積)を計算して値を返す関数を定義し、複数の値を呼び出し結果を確認してください。


In [ ]:
import numpy as np

def vector_dot(v1, v2):
    """2つのベクトルの内積を計算する関数"""
    return np.dot(v1, v2)

# 使用例
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])
result = vector_dot(v1, v2)
print(result)

# 演習3-2
* 行列を転置(ヒント: .T)するメソッドを持つクラスを作成してください。コンストラクタにはその行列を渡し、クラス内で保持して転置メソッドで利用してください。

# 演習3-3
* 行列の要素を二乗してください。

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
res = matrix ** 2
res

# 演習3-4
* 4×4の二次元配列を作成し、2行目から4行目まで、2列目から4列目までの3x3の部分配列を抽出してください。(スライシング)

In [ ]:
import numpy as np

# 2次元配列を作成
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

# 2行目から4行目まで、2列目から4列目までの部分配列を抽出
subarray = arr[1:4, 1:4]
print(subarray)

# 演習3-5
* 1次元配列から奇数インデックスの要素を抽出してください。（ヒント: スライシングとストライド）

In [ ]:
import numpy as np

# 1次元配列を作成
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# ストライド付きスライシングで奇数インデックスの要素を抽出
odd_elements = arr[::2]
print(odd_elements)

# 演習3-6
* 2次元配列（5×5）を1次元配列へ変換してください。
* その際、2次元配列はfor文×2を用いて作成してください。

In [ ]:
import numpy as np

# 空の行列を作成
arr_2d = np.zeros((5, 5), dtype=int)

# for文で値を設定
value = 1
for i in range(5):
    for j in range(5):
        arr_2d[i, j] = value
        value += 1

print("for文で作成した5x5の行列:")
print(arr_2d)
print()

# 2次元配列を1次元配列に変換
arr_1d = arr_2d.reshape(-1)

print("変換後の1次元配列:")
print(arr_1d)